ApplicationsManager/apps/accounts/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.urls import path, include
from ApplicationsManager.apps.accounts import views as account_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'account/login.html'), name = 'login'),
   	path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
	path('register/', account_views.register, name = 'register'),
    path('', account_views.profile, name = 'profile'),
	
	# User lost their account.
	path('lost/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html',
                                                    email_template_name='account/password_reset_email.txt', success_url="/account/lost/done/"), name='password_reset'),
	path('lost/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_email.html'), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'account/password_confirm.html', success_url="/account/reset/done/"), name = 'password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_complete.html'),
	     name='password_reset_complete'),
	
	# A special impersonation feature for superusers.
	path('impersonate/', account_views.impersonate, name='impersonate'),
]

ApplicationsManager/apps/api/urls.py
from django.urls import path, include
from ApplicationsManager.apps.api import views as api_views

urlpatterns = [
    path('search/', api_views.search, name = 'search'),
]

ApplicationsManager/apps/applications/urls.py
from django.contrib import admin
from django.urls import path

from ApplicationsManager.apps.applications import views

urlpatterns = [
	path('', views.index, name='index'),
	path('apply/', views.apply, name = 'apply'),
    path('denial/<applicationid>/', views.denialreason, name='denial'),
	path('view/<applicationid>/', views.viewapplication, name='view'),
]

ApplicationsManager/apps/docs/urls.py
from django.urls import path, include, re_path
from ApplicationsManager.apps.docs import views as doc_views

urlpatterns = [
    path('', doc_views.page, dict(path=''), name = 'index'),
    re_path(r'^(?P<path>[a-zA-Z0-9_\-]+(/[a-zA-Z0-9_\-]+)*)/$', doc_views.page),
]

ApplicationsManager/apps/staffmgmt/urls.py
from django.contrib import admin
from django.urls import path

from ApplicationsManager.apps.staffmgmt import views

urlpatterns = [
	path('', views.viewwriteups, name = 'list'),
	path('view/', views.viewwriteup, name = 'view'),
	path('new/', views.writeup, name='new'),
]

ApplicationsManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ApplicationsManager.apps.api import views as api_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('ApplicationsManager.apps.applications.urls', 'applications'), namespace='applications')),
    path('account/', include(('ApplicationsManager.apps.accounts.urls', 'account'), namespace = 'account')),
    path('writeup/', include(('ApplicationsManager.apps.staffmgmt.urls', 'staffmgmt'), namespace = 'staffmgmt')),
    path('api/', include(('ApplicationsManager.apps.api.urls', 'api'), namespace = 'api')),
    path('doc/', include(('ApplicationsManager.apps.docs.urls', 'docs'), namespace='docs')),
]

# Set our 404 and 500 error pages
handler404 = api_views.page_not_found
handler500 = api_views.server_error

NereusStaffManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from NereusStaffManagement.apps.api import views as api_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('NereusStaffManagement.apps.applications.urls', 'applications'), namespace='applications')),
    path('account/', include(('NereusStaffManagement.apps.accounts.urls', 'account'), namespace = 'account')),
    path('writeup/', include(('NereusStaffManagement.apps.staffmgmt.urls', 'staffmgmt'), namespace = 'staffmgmt')),
    path('api/', include(('NereusStaffManagement.apps.api.urls', 'api'), namespace = 'api')),
    path('doc/', include(('NereusStaffManagement.apps.docs.urls', 'docs'), namespace='docs')),
]

# Set our 404 and 500 error pages
handler404 = api_views.page_not_found
handler500 = api_views.server_error

ApplicationsManager/apps/api/models.py
from django.db import models

# Create your models here.

ApplicationsManager/apps/applications/models.py
from django.db import models
from django.contrib.auth.models import User

TIME_CHOICES = (
	('1', '1-2 Hours'),
	('2', '2-4 Hours'),
	('3', '4-6 Hours'),
	('4', '6-8 Hours'),
	('5', 'More'),
)

APPLICATION_STATUS = (
	('0', 'Pending'),
	('1', 'Denied'),
	('2', 'Approved'),
	('3', 'Cancelled'),
)

# This is a staff application, they will likely
# need to register/login to use this.
class Application(models.Model):

	def __str__(self):
		return "%s on %s -- %s " % (self.username.username, self.datetime.strftime("%l, %F %d, %Y"), self.get_status_display())

	# Email, realname, and such will be included in the user.
	username = models.ForeignKey(User, on_delete=models.DO_NOTHING)

	# The date they decided to make the application
	datetime = models.DateTimeField(auto_now=True)

	# User's in-game name
	ign = models.CharField(max_length=16)

	# User's Age
	age = models.IntegerField()

	# Gender
	gender = models.CharField(max_length=255)

	# Discord name
	discord = models.CharField(max_length=255)

	## Now for the questions in the form. ##

	# Do they have a microphone?
	microphone = models.BooleanField(default=False)
	# What country are they in?
	country = models.CharField(max_length=255, default="United States")
	# Can they screenshare?
	screenshare = models.BooleanField(default=False)
	# How much time can they spend on Nereus?
	timededication = models.CharField(max_length=2, choices=TIME_CHOICES, default='1')
	# Why should we hire them?
	hirereason = models.TextField(null=True)

	# the scenarios
	scenario1 = models.TextField(null=True)
	scenario2 = models.TextField(null=True)
	scenario3 = models.TextField(null=True)

	# Status -- are they pending, approved, or denied?
	status = models.CharField(max_length=2, choices=APPLICATION_STATUS, default='0')
	# The first staff member to approve it
	firstapproval = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="firstapproval", null=True, blank=True)
	# The second staff member to approve it
	secondapproval = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="secondapproval", null=True, blank=True)

	# The approval time
	decisiontime = models.DateTimeField(null=True)

	# If they were not approved, what was their denial reason?
	denialreason = models.TextField(null=True, blank=True)

ApplicationsManager/apps/docs/models.py
from django.db import models

# Create your models here.

ApplicationsManager/apps/staffmgmt/models.py
from django.db import models
from django.contrib.auth.models import User

# The write-up.
class WriteUp(models.Model):
	# The person who made the writeup
	owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="owner")

	# This is only available to upper-staff/management/whatever
	# and will send a notification to the user in question.
	# TODO: This probably needs to DM the user directly once implemented.
	official = models.BooleanField(default=False)

	# the person in question
	suspect = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="suspect")

	# Subject/summary of the writeup. It's limited cuz it's a summary not a fucking novel.
	subject = models.CharField(max_length=128)

	# This is where your novel goes.
	explanation = models.TextField()

ApplicationsManager/apps/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.password_validation import validate_password
from django.contrib import auth
from django.urls import reverse
from django.views import generic
from django import forms

def user_exists(username):
	return User.objects.filter(username=username).exists()

class PasswordChangeForm(forms.Form):
	oldpassword = forms.CharField(max_length=255, label="Old Password", widget=forms.PasswordInput)
	password1 = forms.CharField(max_length=255, label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(max_length=255, label="Password (again)", widget=forms.PasswordInput)

class PersonalInfoChange(ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']
		labels = {
			'email': "E-Mail Address"
		}

# Create your views here.
class RegistrationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', 'username',)

class ImpersonateForm(forms.Form):
	person = forms.CharField(max_length=255, label='Username')

def register(request):
	if request.user.is_authenticated:
		raise Http404("You're already logged in")
	
	form = RegistrationForm(request.POST, initial=request.GET)

	if request.POST and form.is_valid():
		cleaned_data = form.clean()
		if not form.errors:
			if user_exists(cleaned_data.get('username')):
				raise forms.ValidationError("Sorry, this username is taken.")
			else:
				# Do some password validation to ensure it is valid.
				# I thought that the Django form did this but I guess not.
				if not validate_password(cleaned_data.get('password1')):
					raise forms.ValidationError("Your password does not meet the strength requirements.")

				# The user can register, save the form.
				form.save()
				# now log them in.
				user = User.objects.get(username=cleaned_data.get('username'))
				auth.login(request, user)
				# Redirect them to the home.
				return HttpResponseRedirect(reverse('applications:index'))
	else:
		form = RegistrationForm(initial=request.GET)
		
	return render(request, 'account/register.html', {'form': form})


def profile(request):
	passwdfm = PasswordChangeForm(request.POST, initial=request.GET)
	personalfm = PersonalInfoChange(request.POST, instance=request.user)

	if request.POST: 
		if passwdfm.is_valid():
			# user changed their password -- verify the old password and that the passwords match then update it.
			user = authenticate(username=request.user.username, password=passwdfm.cleaned_data.get('oldpassword'))
			
			if not user:
				# Should really change to a notification.
				raise forms.ValidationError("Your password was incorrect.")

			passwd1 = passwdfm.cleaned_data.get('password1')
			passwd2 = passwdfm.cleaned_data.get('password2')

			# Compare the two passwords, this can be done in JS as well but Django does enforcement.
			if passwd1 != passwd2:
				# Should really change to a notification.
				raise forms.ValidationError("Your passwords do not match.")

			if not validate_password(passwd1, user=request.user):
				# Should really change to a notification.
				raise forms.ValidationError("Your password does not meet the strength requirements")

			request.user.set_password(passwd1)
			request.user.save()

			# XXX: TODO: make some kind of notification, probably javascript but this whole func should be AJAX
			# Green Notification box that appears at where it suits best
			return HttpResponseRedirect(reverse("account:profile"))

		if personalfm.is_valid():
			# User updated their information.
			personalfm.save()
			# TODO: make this AJAX instead.
			return HttpResponseRedirect(reverse("account:profile"))
		else:
			raise forms.ValidationError("You have an error in your stuff")

		# They did an invalid submit. Return 404.
		raise Http404()
	else:
		# we have to reinstantiate it because the form will not auto-fill if we do it once.
		personalfm = PersonalInfoChange(instance=request.user)
		return render(request, 'account/profile.html', {'personalinfo': personalfm, 'passwordchange': passwdfm})

def impersonate(request):
	# First check if they're superuser, superuser can do anything
	if request.user.is_superuser:
		# Get the form data
		impernatee = ImpersonateForm(request.POST, initial=request.GET)
		# If they're posting, they're logging in as someone and not grabbing the form.
		if request.POST and impernatee.is_valid():
			# Check if the user exists at all.
			if not user_exists(impernatee.cleaned_data['person']):
				raise forms.ValidationError("User does not exist.")

			# Get that user object from the database
			user = User.objects.get(username=impernatee.cleaned_data['person'])
			# Authenticate them as that user.
			auth.login(request, user)
			# Redirect them to the homepage so they can see that user's home page.
			return HttpResponseRedirect(reverse('applications:index'))
		else:
			return render(request, 'account/impersonate.html', {'form': impernatee})
	else:
		raise Http404()

ApplicationsManager/apps/api/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
from django.template import Template, Context
from django import forms
from django.conf import settings
import requests, json
from ApplicationsManager.apps.applications.models import Application

# This is mostly an internal function for sending messages to discord
def _ManagerMessage(message):
	content = {
		"content":message
	}
	requests.post(settings.DISCORD_WEBHOOK, json=content)

# Just a shortcut function to the above for rendering a templated string.
def _TemplateManagerMessage(messagecode, **kwargs):
	t = Template(messagecode)
	_ManagerMessage(t.render(Context(kwargs)))

# Handle 404 errors
def page_not_found(request, exception):
	return render(request, '404.html', status=404)

# Handle 500 errors
def server_error(request):
	return render(request, '500.html', status=500)

class SearchForm(forms.Form):
	query = forms.CharField(max_length=255)

# Create your views here.
def search(request):
	if request.POST:
		searchq = SearchForm(request.POST)
		if searchq.is_valid():

			query = searchq.cleaned_data.get('query')
			# Okay here's where things get fun. We don't allow the users/staff to view
			# other people's applications, but superusers can view it. This affects
			# search as they should not search for applications by anyone other than themselves.
			objs = None

			if request.user.is_superuser:
				objs1 = Application.objects.filter(discord__icontains=query)
				objs2 = Application.objects.filter(ign__icontains=query)
				objs3 = Application.objects.filter(username__username__icontains=query)
				objs4 = Application.objects.filter(username__first_name__icontains=query)
				objs5 = Application.objects.filter(username__last_name__icontains=query)
				objs6 = Application.objects.filter(username__email__icontains=query)
				objs = objs1 | objs2 | objs3 | objs4 | objs5 | objs6
			else:
				# They're not a superuser, just search within their own applications.
				objs1 = Application.objects.filter(discord__icontains=query, username=request.user)
				objs2 = Application.objects.filter(ign__icontains=query, username=request.user)
				# pointless query but whatever.
				objs3 = Application.objects.filter(username__username__icontains=query, username=request.user)
				objs = objs1 | objs2 | objs3

			
			if not objs:
				return JsonResponse({"status": 0, "msg": "Not Found"})
			
			# We don't just want to blast all the user's info out into the world
			# so first what we do is check if they're admin or not.
			results = []
			for app in objs:
				results.append({
					"username": app.username.username,
					"ign": app.ign,
					"discord": app.discord,
					"applicationid": app.pk,
					"email": app.username.email if request.user.is_superuser else None,
					"firstname": app.username.first_name if request.user.is_superuser else None,
					"lastname": app.username.last_name if request.user.is_superuser else None})
			return JsonResponse({"status": 1, "msg": "Results", "objects": results})
		else:
			return JsonResponse({"status": 0, "msg": "Not Found"})
	else:
		return JsonResponse({"status": 0, "msg": "Invalid request"})

ApplicationsManager/apps/docs/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.conf import settings
from docutils.core import publish_parts
from django.core.cache import cache
from django.template import loader
from django.conf import settings
import os

def page(request, path):
	key = 'ApplicationsManager.apps.doc.page.%s' % (path.replace('/', '.'))
	ctx = cache.get(key)
	# Do not cache when debugging.
	if not ctx or settings.DEBUG:
		filePath = os.path.join(settings.DOCS_ROOT, path)
		print("Attempting to load doc file %s" % filePath)

		# "index" is the document representing its parent
		# directory. We canonicalize URLs here such that they
		# never include "index".
		#
		if os.path.basename(filePath) == 'index':
			return HttpResponseRedirect("..")
		if os.path.isdir(filePath):
			filePath = os.path.join(filePath, 'index')
		if not os.path.isfile(filePath):
			raise Http404

		ctx = render(request, 'docs/doc.html',
		{
			# Render docutils parts
			'parts': publish_parts(
				source=open(filePath).read(),
				writer_name="html4css1",
				settings_overrides={
					'cloak_email_addresses': True,
					'initial_header_level': 2,
				},
			),
		})
		cache.set(key, ctx)
	return ctx

ApplicationsManager/templates/applications/denial.html
{% extends 'base.html' %}
{% load static fuckyouzach %}

{% block head %}
<link rel="stylesheet"  href="{% static "css/denial.css" %}" />
{% endblock %}

{% block body %}
<div class="content">
	<div class="bg-text-top">
		<h1>Reason for denying {{ app.username|getname }}'s application.</h1>
	</div>
	<div class="app-box box">
		<p></p>
		<form method="POST">
		<table>
			<tr>
				<th>{{ form.reason.label_tag }}</th>
				<td>
					{{ form.reason.errors }}
					{{ form.reason }}
				</td>
			</tr>
		</table>
		<button class="button subbutton" type="submit">Submit</button>
		{% csrf_token %}
		</form>
	</div>
</div>

{% endblock %}

ApplicationsManager/templates/applications/finished.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet"  href="{% static "css/apply.css" %}" />
{% endblock %}

{% block body %}
<div class="content">
	<div class="bg-text-top">
		<h1> Nereus Staff Application Form </h1>
	</div>
	<div class="app-box box">
		<h2>Application Submitted</h2>
		<p>
			You will receive a response to your application within 10 days, where you will be informed if you have been invited to an interview,
			or denied with an appropirate reason which you should review if you would like to reapply in the future.<br/>
			
			<span style="color:red;">
			Remember, you are prohibited from discussion of this application in the server
			(Discord, Minecraft, or other). Asking a staff member to review your application or discussion of the
			application in the server will result in an automatic denial with a 2 week waiting period before you may reapply.
			If you attempt to reapply before the the cool-down period expires, you will get an automatic 2 week extension or further action.
			</span>
		</p>
	</div>
</div>

{% endblock %}

ApplicationsManager/templates/applications/index.html
{% extends 'base.html' %}
{% load static %}
{% load fuckyouzach %}

{% block head %}
<link rel="stylesheet"  href="{% static "css/index.css" %}" />
<title>Nereus Staff | Index</title>
{% endblock %}

{% block body %}
<div class="content">
	<div class="bg-text">
		<div class="sidebarright box">
			<fieldset>
				<legend>Links</legend>
				<p>Places to go</p>
				<hr/>
				<ul>
					{% if not user.is_staff and not user.is_superuser %}
						{# only show "Apply to staff" to the randos #}
						<li><a href="{% url 'applications:apply' %}">Apply to be a staff member</a></li>
					{% elif user.is_superuser %}
						<li><a href="{% url 'account:impersonate' %}">Impersonate a user</a></li>
						<li><a href="{% url 'admin:index' %}">Django Administration</a></li>
						<hr/>
						<li><a href="{% url 'staffmgmt:list' %}">View Writeups</a></li>
						<li><a href="{% url 'account:login' %}">View ban/punishment disputes (COMING SOON!)</a></li>
					{% else %}
						<li><a href="{% url 'staffmgmt:new' %}">Report another staff member</a></li>
						<li><a href="{% url 'account:login' %}">View ban/punishment disputes (COMING SOON!)</a></li>
					{% endif %}
				</ul>
			</fieldset>
		</div>

		<div class="sidebarleft box">
			<h2>Your applications</h2>
			<ol>
				{% if yourapps %}
					{% for app in yourapps %}
						<li>You filed an application on {{ app.datetime | date }}. Application status: 
							{% if app.status == '0' %}
								<span id="pending">{{ app.get_status_display }}</span>
							{% elif app.status == '1' %}
								<span id="denied">{{ app.get_status_display }}</span>
							{% elif app.status == '3' %}
								<span id="cancelled">{{ app.get_status_display }}</span>
							{% else %}
								<span id="accepted">{{ app.get_status_display }}</span>
							{% endif %}
								-- <a href="{% url 'applications:view' applicationid=app.pk %}">view</a></li>
					{% endfor %}
				{% else %}
					<li>You do not have any applicatons. <a href="{% url 'applications:apply' %}">Would you like to apply to Nereus Staff?</a></li>
				{% endif %}
			</ol>
		</div>
	</div>

	{% if perms.applications.viewapps %}
		<div class="listbox box">
			<h2>Applications Pending Review</h2>
			<ol>
				{% if apps %}
					{% for deal in apps %}
						{% if deal.status == '0' %}
							<li>{{ deal.username|getname }} made an application on {{ deal.datetime|date:"l, F d, Y" }} -- <a href="{% url 'applications:view' applicationid=deal.pk %}">view application</a></li>
						{% endif %}		
					{% endfor %}
				{% else %}
					<li>There are apparently no existing applications.</li>
				{% endif %}
			</ol>
		</div>

		<div class="listbox box">
			<h2>Recently Denied Applications</h2>
			<ol>
				{% if apps %}
					{% for deal in apps %}
						{% if deal.status == '1' %}
							<li>{{ deal.username|getname }} had their application denied on {{ deal.decisiontime|date:"l, F d, Y" }} -- <a href="{% url 'applications:view' applicationid=deal.pk %}">view</a></li>
						{% endif %}
					{% endfor %}
				{% else %}
					<li>There are apparently no existing applications.</li>
				{% endif %}
			</ol>
		</div>
		
		<div class="listbox box">
			<h2>Recently Accepted Applications</h2>
			<ol>
				{% if apps %}
					{% for deal in apps %}
						{% if deal.status == '2' %}				
							<li>{{ deal.username|getname }} had their application accepted on {{ deal.decisiontime|date:"l, F d, Y" }} -- <a href="{% url 'applications:view' applicationid=deal.pk %}">view</a></li>
						{% endif %}
					{% endfor %}
				{% else %}
					<li>There are apparently no existing applications.</li>
				{% endif %}
			</ol>
		</div>
	{% endif %}
</div>
{% endblock %}

ApplicationsManager/templates/applications/view.html
{% extends 'base.html' %}
{% load static fuckyouzach humanize %}

{% block head %}
<link rel="stylesheet"  href="{% static "css/view.css" %}" />
<title>Nereus Staff | {{ application.username|getname }}'s Application</title>
{% endblock %}

{% block body %}
<div class="content">
	<center><div class="bg-text-top">
		<h2> {{ application.username|getname }} ({{ application.username.username }})'s Staff Application </h2>
	</div></center>
	<div class="bg-text box">
	<h3>Application Information</h3>
	<div class="item">
		<span class="label">Status:</span> 
		{% if application.status == '0' %}
			<span id="pending">{{ application.get_status_display }}</span>
		{% elif application.status == '1' %}
			<span id="denied">{{ application.get_status_display }}</span>
		{% elif application.status == '3' %}
			<span id="cancelled">{{ application.get_status_display }}</span>
		{% else %}
			<span id="accepted">{{ application.get_status_display }}</span>
		{% endif %}
	</div>
	{% if application.firstapproval %}
		<div class="item"><span class="label">{% if application.status == '1' %}Denied by{% else %}First Approval{% endif %}:</span> {{ application.firstapproval|getname }}</div>
	{% endif %}
	{% if application.secondapproval and application.status != '1' %}
		<div class="item"><span class="label">Second Approval:</span> {{ application.secondapproval|getname }}</div>
	{% endif %}
	{# Show the denial time #}
	{% if application.status == '1' %}
		<div class="item"><span class="label">Denied at:</span> {{ application.decisiontime|date:"l, F d, Y g:i:s a e" }} ({{ application.decisiontime|naturaltime }})</div>
	{% elif application.status == '2' %}
		<div class="item"><span class="label">Accepted on:</span> {{ application.decisiontime|date:"l, F d, Y g:i:s a e" }} ({{ application.decisiontime|naturaltime }})</div>
	{% endif %}
	{# Show the denial reason #}
	{% if application.denialreason %}
		<div class="item"><span class="label">Denial Reason:</span><br/> {{ application.denialreason }}</div>
	{% endif %}
	<h3>Background Information</h3>
		<div class="item"><span class="label">Username:</span> {{ application.username.username }}</div>
		<div class="item"><span class="label">Real Name:</span> {{ application.username.get_full_name }}</div>
		<div class="item"><span class="label">Country:</span> {{ application.country }}</div>
		<div class="item"><span class="label">Email:</span> {{ application.username.email }}</div>
		<div class="item"><span class="label">Date Applied:</span> {{ application.datetime | date }}</div>
		<div class="item"><span class="label">In-Game Name:</span> {{ application.ign }}</div>
		<div class="item"><span class="label">Age:</span> {{ application.age }}</div>
		<div class="item"><span class="label">Gender:</span> {{ application.gender }}</div>
		<div class="item"><span class="label">Discord handle:</span> {{ application.discord }}</div>
		<br/>
		<div class="item"><span class="label">Has microphone:</span> {{ application.microphone | yesno }}</div>
		<div class="item"><span class="label">Can Screenshare:</span> {{ application.Screenshare | yesno }}</div>
		<div class="item"><span class="label">Time Dedication:</span> {{ application.get_timededication_display }}</div>
		<br/>
	<h3>All About You</h3>
		<span class="label">Is there anything specific that inspired you to want to join the staff team?</span><br/>
		{{ application.hirereason }}<br/>
		<br/>
		<span class="label">A player has begun an argument with another player and now they are both arguing in the chat constantly. What do you do?</span><br/>
		{{ application.scenario1 }}<br/>
		<br/>
		<span class="label">A player has found a bug and they have continued to abuse the bug without telling any staff. What do you do?</span><br/>
		{{ application.scenario2 }}<br/>
		<br/>
		<span class="label">A player has been caught scamming others for in-game items causing other players to get annoyed and toxic in the chat. What do you do?</span><br/>
		{{ application.scenario3 }}<br/>
	</div>
	{% if application.status == '0' and user.is_superuser %}
		<form method="POST">
			{% csrf_token %}
			<button name="AcceptApplication" type="submit">Accept</button> <button name="DenyApplication" type="submit">Deny</button>
		</form>
	{% elif application.status == '0' and user == application.username %}
		<form method="POST">
			{% csrf_token %}
			<button name="CancelApplication" type="submit">Cancel</button>
		</form>
	{% endif %}
</div>
{% endblock %}